### ISSUE TITLE
angular is not defined when running $ionic serve

### ISSUE THREAD

**Issue by physicsdude** [feruzm/esteem#3]
master$ionic serve
c
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/_, !www/__/_.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ Console log output: enabled
Loading: /?restart=239030
ionic $ 0     405659   error    Uncaught ReferenceError: angular is not defined, http://localhost:8100/js/lib.js, Line: 247
1     405686   error    Uncaught ReferenceError: angular is not defined, http://localhost:8100/lib/wizMarkdown.js, Line: 5801
2     405812   error    Uncaught ReferenceError: angular is not defined, http://localhost:8100/js/index.js, Line: 26843
3     405819   error    Uncaught TypeError: Cannot read property 'module' of undefined, http://localhost:8100/lib/rzslider.min.js, Line: 2

**Comment by feruzm** [comment]
Hi @physicsdude Sorry have missed your issue report.

Have you tried ?
`npm install`

`bower install`

`gulp scripts`

and then

`ionic serve`

that should generate necessary script files.

**Comment by physicsdude** [comment]
Its working now... see my pull request :^)
