### ISSUE TITLE
No Refresh on Main View

### ISSUE THREAD

**Issue by kharoof** [feruzm/esteem#35]
When I scroll down I can see infinite posts on my main view. but when I scroll to the top it doesn't refresh if I pull down. To get it to refresh I need to click Feed then select Feed again. It would be more intuitive if when I scrolled to the top then pulled down the feed updated/refreshed.

**Comment by kharoof** [comment]
Just to add to this issue that it seems to happen on all page views in the app and on the home page also. 
It would also be useful if there was some notification showing last updated 1 sec ago or similar at the bottom of the app.

**Comment by feruzm** [comment]
Should now be available with v1.3.7

**Comment by tibonova** [comment]
It still doesn't work for me.
