### ISSUE TITLE
Show the version number under "About"

### ISSUE THREAD

**Issue by tibonova** [feruzm/esteem#40]
I can find it on Android easily because I'm a tech guy, but soon there will be more users who are less competent in these things and afraid going deeper in their OS settings menu than Wifi on/off. The custom Android UIs just worsen on this issue (especially on the side of Support). 

The first question I would ask from a user who has issues is:
> Do you use the latest version of the app? 

They must find it out easily and quickly.

**Comment by feruzm** [comment]
v1.3.8 have this in About page title, please confirm if it is helpful, although we had version number bottom of side menu on left.

**Comment by tibonova** [comment]
Hmmm, I didn't see that, and I should see that when I had scrolled to About at the bottom... Maybe it's just the habit to looking for it in the About.

I like the change though, because that is the standard place of the version number, and it's even emphasized in the title. :+1:
