### ISSUE TITLE
Splash screen logo and text to close too device borders (iOS)

### ISSUE THREAD

**Issue by testzcrypto** [feruzm/esteem#6]
Please make logo and text little smaller and add margins.

**Comment by feruzm** [comment]
noted, thanks... will update splash screen on next release

**Comment by testzcrypto** [comment]
Probably we need to add some margins into icon as well, currently it's looks:

![](https://cdn.pbrd.co/images/6UB2fC84F.png)

**Comment by feruzm** [comment]
Yes, you are right... will work on logo and splash graphics
