### ISSUE TITLE
No error message when login with posting key and submit story

### ISSUE THREAD

**Issue by testzcrypto** [feruzm/esteem#7]
Step to reproduce:
1. Login in advanced mode using posting key
2. Select **Submit a story**

Tested at iOS device.

**Comment by feruzm** [comment]
Did submit story fail? Generally, posting key and main password is check before broadcasting transaction and if transaction is successfully signed then broadcast goes through.

**Comment by testzcrypto** [comment]
Probably, thought for a second and nothing happened.

**Comment by feruzm** [comment]
Did login screen closed? if not, then there is an issue with devicetoken, which I am testing now...

**Comment by testzcrypto** [comment]
Login ok, after login with posting key then I click **Submit a story** menu - it's thought for a second and nothing happened.

**Comment by feruzm** [comment]
Oh right, sorry! Yes it has been reported and fixed, should work with upcoming release v1.3.3 https://github.com/feruzm/esteem/commit/1906018af0439f36a172b9cd9d05332b102ba90a
